### ISSUE TITLE
No connection to notes behind htpauth protected url

### ISSUE THREAD

**Issue by modzilla99** [patrikx3/onenote#151]
Hey there,

my company uses basic http authentication to secure our sharepoint with which can easily be tried with traefik. I've attached a docker-compose file which has it turned on and catches all requests on :443 and :80. So you could try with that. I'd love to submit a pr but I'm not good at that, sorry :(

The prerequisites are docker + docker-compose (The repo version is too old in ubuntu but setting version from 3 to 2 might work nevertheless) 

```yaml
version: '3'
services: 
    traefik:
        hostname: traefik
        image: library/traefik:2.4
        restart: always
        ports:
            - "80:80"
            - "443:443"
        command:
            - "--log.level=INFO"
            - "--providers.docker=true"
            - "--api.debug=true"
            - "--providers.docker.exposedByDefault=false"
            - "--api.dashboard=true"
            - "--providers.file.watch=true"
            - "--providers.file.filename=/etc/traefik/file-provider.yml"
            - "--entrypoints.web.address=:80"
            - "--entrypoints.websecure.address=:443"
            - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
            - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
            - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.api-secure.rule=Host(`*`)"
            - "traefik.http.routers.api-secure.tls=true"
            - "traefik.http.routers.api-secure.service=api@internal"
            - "traefik.http.routers.api-secure.middlewares=auth"
            - "traefik.http.middlewares.auth.basicauth.users=user:$$apr1$$oGqr2R7d$$WFmxm3ivkJue7fEgijYvk."
```
