### ISSUE TITLE
Onenote not starting, ldconfig failed, exit status 35584, Bluefin linux (fedora)

### ISSUE THREAD

**Issue by maphew** [patrikx3/onenote#223]
I installed using flatpak on Bluefin linux (bluefin-dx 40). A launch app is created but using it has no effect, there are no error messages.

```
flatpak info com.patrikx3.onenote
          ID: com.patrikx3.onenote
         Ref: app/com.patrikx3.onenote/aarch64/master
        Arch: aarch64
      Branch: master
      Origin: onenote-origin
  Collection: 
Installation: system
   Installed: 331.5 MB
     Runtime: org.freedesktop.Platform/aarch64/20.08
         Sdk: org.freedesktop.Sdk/aarch64/20.08

      Commit: 05d382b9cd8408ac5eeebc81b514e9c2254af7199dfc78276a9d621e79bda035
     Subject: Export com.patrikx3.onenote
        Date: 2025-01-21 14:39:36 +0000
```
